# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use a specific tag or commit hash
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 24.4.2 # Specify Black version
    hooks:
    -   id: black
        language_version: python3.11 # Match your project's Python version if needed

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2 # Specify isort version
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"] # Make isort compatible with Black

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.0 # Specify flake8 version
    hooks:
    -   id: flake8
        # Optionally add args for configuration (e.g., --max-line-length=88)
        # args: ["--max-line-length=88", "--ignore=E203,W503"] # Example: ignore E203,W503, match Black's line length
        # Consider using a setup.cfg or pyproject.toml for flake8 config instead

# Optional: Add safety for local vulnerability checks on commit (can be slow)
# -   repo: https://github.com/pycqa/safety
#     rev: 3.1.0 # Specify safety version
#     hooks:
#       - id: safety
#         args: ["check", "--file=requirements/base.txt", "--full-report"]
#         # You might want separate hooks for local.txt / prod.txt if needed

# Optional: Add Bandit for security linting
# -   repo: https://github.com/PyCQA/bandit
#     rev: 1.7.9 # Specify bandit version
#     hooks:
#       - id: bandit
#         args: ["-c", "pyproject.toml"] # Requires bandit config in pyproject.toml
#         exclude: tests/ # Exclude test directories if needed 